### ISSUE TITLE
Use "nestedSamplingInternal" for a specific use

### ISSUE THREAD

**Issue by sunandopatra** [ssmit1986/BayesianInference#2]
Hi  Sjoerd,
I was going through the package and frankly, am fascinated by it. I have been in the process of developing a package for specific use in my community and was implementing MCMC with Metropolis using brute force codes. The "Statistics`MCMC`BuildMarkovChain" function really was a pleasant surprise. 
I really want to implement the "nestedSamplingInternal" function in part of my code and future analyses. I will do the necessary adjustments for a seamless workflow in mine, but would it be okay if I do that with the proper citation? Please let me know as I could not find your email and there is no DM option here. my email: sunando.patra@gmail.com

Regards, 
Sunando

**Comment by ssmit1986** [comment]
Hi Sunando,

Thanks for your feedback! Please feel free to use whatever you need from my code. Just cite my name and the github link and that should be fine as far as I'm concerned. Of course it would be a good idea to mention Skilling's original paper about nested sampling as well, since that's basically my source.

I'm currently not developing it very actively, but if you find any problems or have any questions, you can always contact me through Github or on my private e-mail address (I'll send you an e-mail after this). 

I wish you all the best with your project!
Sjoerd
